server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/s_estoque?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true
      database: mysql
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    hostname: host.docker.internal
   client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://host.docker.internal:8761/eureka}    


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
